# Generated by Django 5.1.2 on 2024-11-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.TextField(default='Seattle'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.TextField(default='Awesome Oppossum'),
        ),
    ]
