# Generated by Django 5.1.2 on 2024-11-05 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('phase', models.CharField(max_length=100)),
                ('moonrise', models.TimeField(blank=True, null=True)),
                ('moonset', models.TimeField(blank=True, null=True)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('illumination', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ritual_text', models.TextField()),
                ('intent_text', models.TextField()),
                ('reflect_text', models.TextField()),
                ('manifest_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moon_phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moonside.moonphase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
