# Generated by Django 5.1.2 on 2024-11-07 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjournalentry',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
