# Generated by Django 5.1.2 on 2024-11-07 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonside', '0002_userjournalentry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moonphase',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userjournalentry',
            name='id',
        ),
        migrations.AddField(
            model_name='moonphase',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='userjournalentry',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
